# Generated by Django 3.1.1 on 2020-09-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='job',
            name='framework',
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='solar installation', max_length=100),
        ),
    ]
