# Generated by Django 3.0.6 on 2021-03-21 21:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('summary', models.TextField(default='Good read', max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('body', ckeditor.fields.RichTextField(blank=True, help_text='share link of images that are light', max_length=1500)),
                ('image', models.ImageField(help_text='drastically reduce the quality of the image to nothing more than 100kb', upload_to='images/')),
                ('alternative_text', models.CharField(default='dreamfix', help_text='cation the image', max_length=15)),
                ('home_display', models.BooleanField(default=False, help_text='when this is ticked, the image appears at the home page article index')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=30)),
                ('body', models.TextField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='post_category',
            field=models.ManyToManyField(default='solar', to='blog.Category'),
        ),
    ]
